### ISSUE TITLE
SVG Export not working in Houdini 20

### ISSUE THREAD

**Issue by useronym** [Aeoll/Aelib#20]
Error running callback:
```
Traceback (most recent call last):
  File "ae::Sop/SVG_Export::3/saveButton", line 1, in <module>
  File "C:\PROGRA~1/Side Effects Software/Houdini 20.0.590/houdini/python3.10libs\hou.py", line 54951, in __getattr__
    return _hou.HDAModule___getattr__(self, name)
AttributeError: 'module' object has no attribute 'exportSVG'
```

**Comment by proceduralworks** [comment]
Having the same issue...

**Comment by julianwilliams** [comment]
same issue in 19.5/20 in both 3.9.and 3.10 builds.

**Comment by kitaedesigns** [comment]
Upvote

**Comment by julianwilliams** [comment]
upvote

**Comment by Aeoll** [comment]
Should be fixed in latest release
